### ISSUE TITLE
i have some warning with "e-pie" ?

### ISSUE THREAD

**Issue by bombkiml** [eagle1949/x-echarts#1]
I have some warning when using "e-pie" like this
![image](https://github.com/eagle1949/x-echarts/assets/34172506/f0c3df64-5da6-4781-9c08-6c111be5337a)

Please solve it.

Ref: : https://github.com/apache/echarts/issues/15301

Thanks for solve it.

**Comment by bombkiml** [comment]
@eagle1949

**Comment by eagle1949** [comment]
> I have some warning when using "e-pie" like this ![image](https://private-user-images.githubusercontent.com/34172506/300388300-f0c3df64-5da6-4781-9c08-6c111be5337a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjIxODgsIm5iZiI6MTcwNjg2MTg4OCwicGF0aCI6Ii8zNDE3MjUwNi8zMDAzODgzMDAtZjBjM2RmNjQtNWRhNi00NzgxLTljMDgtNmMxMTFiZTUzMzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA4MTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlOGRhYzcyOTVjYzkyNzk4Y2E1MjE4NDk3MWJiNGY2MTAyOTkxOGU0ZWRhOTM4OTBiYTUzNDNlYjkwZmI0MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T6ek7CClNAfNoagXkNOeGDsslBqtkp8gyBFKTJJlPSA)
> 
> Please solve it.
> 
> Ref: : [apache/echarts#15301](https://github.com/apache/echarts/issues/15301)
> 
> Thanks for solve it.

OK，I will fixed it last version

**Comment by eagle1949** [comment]
> I have some warning when using "e-pie" like this ![image](https://private-user-images.githubusercontent.com/34172506/300388300-f0c3df64-5da6-4781-9c08-6c111be5337a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjM0MjIsIm5iZiI6MTcwNjg2MzEyMiwicGF0aCI6Ii8zNDE3MjUwNi8zMDAzODgzMDAtZjBjM2RmNjQtNWRhNi00NzgxLTljMDgtNmMxMTFiZTUzMzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA4Mzg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YzliY2ZiMTA3YTJkZjljZTIxYTEzZmI0NGExZTdlY2YxZjE5Nzc0MTZiNzc0OTQ4ODU0NDk5YTlhN2U0YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J-WSenE2MluzzOZHEMnAIIqBAfzRBtAEoVDXze1M1MY)
> 
> Please solve it.
> 
> Ref: : [apache/echarts#15301](https://github.com/apache/echarts/issues/15301)
> 
> Thanks for solve it.

try the V1.0.6  
![image](https://github.com/eagle1949/x-echarts/assets/13437071/99b56390-311b-4a2d-b276-3872c91c915f)

**Comment by bombkiml** [comment]
> > I have some warning when using "e-pie" like this ![image](https://private-user-images.githubusercontent.com/34172506/300388300-f0c3df64-5da6-4781-9c08-6c111be5337a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjM0MjIsIm5iZiI6MTcwNjg2MzEyMiwicGF0aCI6Ii8zNDE3MjUwNi8zMDAzODgzMDAtZjBjM2RmNjQtNWRhNi00NzgxLTljMDgtNmMxMTFiZTUzMzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA4Mzg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YzliY2ZiMTA3YTJkZjljZTIxYTEzZmI0NGExZTdlY2YxZjE5Nzc0MTZiNzc0OTQ4ODU0NDk5YTlhN2U0YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J-WSenE2MluzzOZHEMnAIIqBAfzRBtAEoVDXze1M1MY)
> > Please solve it.
> > Ref: : [apache/echarts#15301](https://github.com/apache/echarts/issues/15301)
> > Thanks for solve it.
> 
> try the V1.0.6 ![image](https://private-user-images.githubusercontent.com/13437071/301782056-99b56390-311b-4a2d-b276-3872c91c915f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODcwNTgsIm5iZiI6MTcwNjg4Njc1OCwicGF0aCI6Ii8xMzQzNzA3MS8zMDE3ODIwNTYtOTliNTYzOTAtMzExYi00YTJkLWIyNzYtMzg3MmM5MWM5MTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE1MTIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0OWI3NjJjZjFjNzMwNDE2ODA5OTVlMzNlYTcyNzg5ODJkMDZhN2UzMTBmNzBmNDA3OGRkMjFhZTcwMDIzMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x6rV46RWz0L6kt5SmV7X2fFstTMjwCvH_Ypqmm0RCXw)

Ok, It's work !!


--------------------------------------------------
And Please close Log console this. 

![image](https://github.com/eagle1949/x-echarts/assets/34172506/25225111-66c0-421f-a7b2-ed2c3d44aac7)

Thanks.

**Comment by eagle1949** [comment]
> > > I have some warning when using "e-pie" like this ![image](https://private-user-images.githubusercontent.com/34172506/300388300-f0c3df64-5da6-4781-9c08-6c111be5337a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjM0MjIsIm5iZiI6MTcwNjg2MzEyMiwicGF0aCI6Ii8zNDE3MjUwNi8zMDAzODgzMDAtZjBjM2RmNjQtNWRhNi00NzgxLTljMDgtNmMxMTFiZTUzMzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA4Mzg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YzliY2ZiMTA3YTJkZjljZTIxYTEzZmI0NGExZTdlY2YxZjE5Nzc0MTZiNzc0OTQ4ODU0NDk5YTlhN2U0YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J-WSenE2MluzzOZHEMnAIIqBAfzRBtAEoVDXze1M1MY)
> > > Please solve it.
> > > Ref: : [apache/echarts#15301](https://github.com/apache/echarts/issues/15301)
> > > Thanks for solve it.
> > 
> > 
> > try the V1.0.6 ![image](https://private-user-images.githubusercontent.com/13437071/301782056-99b56390-311b-4a2d-b276-3872c91c915f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODcwNTgsIm5iZiI6MTcwNjg4Njc1OCwicGF0aCI6Ii8xMzQzNzA3MS8zMDE3ODIwNTYtOTliNTYzOTAtMzExYi00YTJkLWIyNzYtMzg3MmM5MWM5MTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE1MTIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0OWI3NjJjZjFjNzMwNDE2ODA5OTVlMzNlYTcyNzg5ODJkMDZhN2UzMTBmNzBmNDA3OGRkMjFhZTcwMDIzMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x6rV46RWz0L6kt5SmV7X2fFstTMjwCvH_Ypqmm0RCXw)
> 
> Ok, It's work !!
> 
> And Please close Log console this.
> 
> ![image](https://private-user-images.githubusercontent.com/34172506/301888285-25225111-66c0-421f-a7b2-ed2c3d44aac7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODkwODIsIm5iZiI6MTcwNjg4ODc4MiwicGF0aCI6Ii8zNDE3MjUwNi8zMDE4ODgyODUtMjUyMjUxMTEtNjZjMC00MjFmLWE3YjItZWQyYzNkNDRhYWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE1NDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYzA4NWZjZjAzNWU5MDEwYTExMWIxMTE3NmFmMThlYzk2ZDU0MzFhZGM3MGViNDNhMjhhMTM5ZWUwMzhkYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VpvwjIpAAwuAE5m0SMqUgJrCNQ7sdqbWRkUD5D2ywtU)
> 
> Thanks.

ok，I will close all，next versioin

**Comment by eagle1949** [comment]
> > > I have some warning when using "e-pie" like this ![image](https://private-user-images.githubusercontent.com/34172506/300388300-f0c3df64-5da6-4781-9c08-6c111be5337a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjM0MjIsIm5iZiI6MTcwNjg2MzEyMiwicGF0aCI6Ii8zNDE3MjUwNi8zMDAzODgzMDAtZjBjM2RmNjQtNWRhNi00NzgxLTljMDgtNmMxMTFiZTUzMzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA4Mzg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YzliY2ZiMTA3YTJkZjljZTIxYTEzZmI0NGExZTdlY2YxZjE5Nzc0MTZiNzc0OTQ4ODU0NDk5YTlhN2U0YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J-WSenE2MluzzOZHEMnAIIqBAfzRBtAEoVDXze1M1MY)
> > > Please solve it.
> > > Ref: : [apache/echarts#15301](https://github.com/apache/echarts/issues/15301)
> > > Thanks for solve it.
> > 
> > 
> > try the V1.0.6 ![image](https://private-user-images.githubusercontent.com/13437071/301782056-99b56390-311b-4a2d-b276-3872c91c915f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODcwNTgsIm5iZiI6MTcwNjg4Njc1OCwicGF0aCI6Ii8xMzQzNzA3MS8zMDE3ODIwNTYtOTliNTYzOTAtMzExYi00YTJkLWIyNzYtMzg3MmM5MWM5MTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE1MTIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0OWI3NjJjZjFjNzMwNDE2ODA5OTVlMzNlYTcyNzg5ODJkMDZhN2UzMTBmNzBmNDA3OGRkMjFhZTcwMDIzMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x6rV46RWz0L6kt5SmV7X2fFstTMjwCvH_Ypqmm0RCXw)
> 
> Ok, It's work !!
> 
> And Please close Log console this.
> 
> ![image](https://private-user-images.githubusercontent.com/34172506/301888285-25225111-66c0-421f-a7b2-ed2c3d44aac7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODkwODIsIm5iZiI6MTcwNjg4ODc4MiwicGF0aCI6Ii8zNDE3MjUwNi8zMDE4ODgyODUtMjUyMjUxMTEtNjZjMC00MjFmLWE3YjItZWQyYzNkNDRhYWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE1NDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYzA4NWZjZjAzNWU5MDEwYTExMWIxMTE3NmFmMThlYzk2ZDU0MzFhZGM3MGViNDNhMjhhMTM5ZWUwMzhkYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VpvwjIpAAwuAE5m0SMqUgJrCNQ7sdqbWRkUD5D2ywtU)
> 
> Thanks.

OK，1.0.7 fixed this,try it

**Comment by bombkiml** [comment]
> > > > I have some warning when using "e-pie" like this ![image](https://private-user-images.githubusercontent.com/34172506/300388300-f0c3df64-5da6-4781-9c08-6c111be5337a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjM0MjIsIm5iZiI6MTcwNjg2MzEyMiwicGF0aCI6Ii8zNDE3MjUwNi8zMDAzODgzMDAtZjBjM2RmNjQtNWRhNi00NzgxLTljMDgtNmMxMTFiZTUzMzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA4Mzg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YzliY2ZiMTA3YTJkZjljZTIxYTEzZmI0NGExZTdlY2YxZjE5Nzc0MTZiNzc0OTQ4ODU0NDk5YTlhN2U0YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J-WSenE2MluzzOZHEMnAIIqBAfzRBtAEoVDXze1M1MY)
> > > > Please solve it.
> > > > Ref: : [apache/echarts#15301](https://github.com/apache/echarts/issues/15301)
> > > > Thanks for solve it.
> > > 
> > > 
> > > try the V1.0.6 ![image](https://private-user-images.githubusercontent.com/13437071/301782056-99b56390-311b-4a2d-b276-3872c91c915f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODcwNTgsIm5iZiI6MTcwNjg4Njc1OCwicGF0aCI6Ii8xMzQzNzA3MS8zMDE3ODIwNTYtOTliNTYzOTAtMzExYi00YTJkLWIyNzYtMzg3MmM5MWM5MTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE1MTIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0OWI3NjJjZjFjNzMwNDE2ODA5OTVlMzNlYTcyNzg5ODJkMDZhN2UzMTBmNzBmNDA3OGRkMjFhZTcwMDIzMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x6rV46RWz0L6kt5SmV7X2fFstTMjwCvH_Ypqmm0RCXw)
> > 
> > 
> > Ok, It's work !!
> > And Please close Log console this.
> > ![image](https://private-user-images.githubusercontent.com/34172506/301888285-25225111-66c0-421f-a7b2-ed2c3d44aac7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODkwODIsIm5iZiI6MTcwNjg4ODc4MiwicGF0aCI6Ii8zNDE3MjUwNi8zMDE4ODgyODUtMjUyMjUxMTEtNjZjMC00MjFmLWE3YjItZWQyYzNkNDRhYWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE1NDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYzA4NWZjZjAzNWU5MDEwYTExMWIxMTE3NmFmMThlYzk2ZDU0MzFhZGM3MGViNDNhMjhhMTM5ZWUwMzhkYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VpvwjIpAAwuAE5m0SMqUgJrCNQ7sdqbWRkUD5D2ywtU)
> > Thanks.
> 
> OK，1.0.7 fixed this,try it


Wow, So fast solved, That beautiful 
Thank you so much.
And Thank you for create The awesome lib.
